### ISSUE TITLE
Specify Templates as Input Variables

### ISSUE THREAD

**Issue by jseiser** [mimacom/ansible-role-bamboo#3]
It would be great if it was possible to override your server.xml template.  I think if it was defined as a variable, and then that variable was used in the task it would work.  You could of course keep yours as default.  I think this would allow more flexibility than me submitting pull requests to add additional variables to the template.

**Comment by stromvirvel** [comment]
I think I'd rather use server.xml shipped by Atlassian and change the values using XML module. But of course we could add the option to use another source. From where would you download the custom server.xml? Can you send me a proposal with a pull request?
