### ISSUE TITLE
Error on Task

### ISSUE THREAD

**Issue by Beast12** [mimacom/ansible-role-bamboo#7]
Hi,
I've got following error while executing the bamboo role:
TASK [ansible-role-bamboo : Install bamboo systemd unit script] ******************************************************
task path: /home/ansible/ansible-roles/ansible-role-bamboo/tasks/bamboo.yml:64

fatal: [bamboo02dev.brusselsairport.aero]: FAILED! => {
    "changed": false, 
    "msg": "AnsibleUndefinedVariable: 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'protocol'"
}

System where bamboo is trying to be installed:
[root@bamboo02dev bamboo]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 

Kind regards

**Comment by stromvirvel** [comment]
Hi @Beast12 

Can you send me the output of `ansible --version` ?

**Comment by Beast12** [comment]
Hi @moepot 
CentOS Linux release 7.4.1708 (Core) 
[ansible@ansible01prod ansible-playbooks]$ ansible --version
ansible 2.6.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

**Comment by Beast12** [comment]
Hi @moepot 
Problem found. The http_proxy variable was declared in another role in our roles dir... Sorry..

Kind regards,
